// Mocks generated by Mockito 5.0.12 from annotations
// in movies_picker_client/test/test_utils.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies_picker_client/data/api/movies_api.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResponse extends _i1.Fake implements _i2.Response {}

/// A class which mocks [MoviesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesApi extends _i1.Mock implements _i3.MoviesApi {
  MockMoviesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> getMovieDetails(int? movieId) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetails, [movieId]),
              returnValue: Future<_i2.Response>.value(_FakeResponse()))
          as _i4.Future<_i2.Response>);
}
