name: movies_picker_client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logger: ^1.0.0
  http: ^0.13.3
  provider: ^5.0.0
  flutter_bloc: ^7.0.1
  font_awesome_flutter: ^9.1.0
  flutter_rating_stars: ^1.0.3+4
  flutter_image_slideshow: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.10
  mockito: ^5.0.12
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

dependency_overrides:
  test_api: 0.4.2

flutter:

  uses-material-design: true

  assets:
     - assets/images/coming_soon.png
